# 服务端口
server:
  port: 8005

spring:
  # 服务名
  application:
    name: service-sms
  # 环境设置：dev（开发环境）、test（测试环境）、prod（生产环境）
  profiles:
    active: dev
  # 设置Json的时间格式（默认为标准时区，例2019-11-12T05:36:36.000+0000）
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 例：2021-10-27 23:47:52
    time-zone: GMT+8 # 设置时区为东八区
  # 将服务注册到nacos中
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos地址
  # 配置redis地址
  redis:
    host: 47.97.182.0
    port: 6379
    database: 0
    password: 123456
    timeout: 1800000 # 超时时间